
library(ggplot2)
library(binr)
library(dplyr)
library(DT)
library(tools)
library(RColorBrewer)
library(readxl)
library(reshape2)
library(tidyr)
library (scales)
library(latticeExtra)
library(cowplot)
source("3D_helper.R")
source("piebarHelper.R")
library(knitr)
library(kableExtra)
library(DT)
library(GGally)
library(readxl)
theme_set(theme_minimal())

knitr::opts_chunk$set(echo = TRUE, fig.align='center', out.width = "75%", out.height = "75%", fig.width = 5, fig.height = 4)
#render your sweet site. 
rmarkdown::render_site()
